# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.8'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
  
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: bookstore:latest
    ports:
      - "8080:80"
    depends_on:
      - postgresql

volumes:
  postgresql_data:
    driver: local
